README.md, lib/literal/structish.rb, test/literal/data.test.rb, test/literal/struct.test.rb
=> Add `#deconstruct` and `#deconstruct_keys` to Structish classes

lib/literal/types.rb, lib/literal/types/range_type.rb
=> Add generic `_Range` type

lib/literal/structish.rb, test/literal/data.test.rb
=> Implement hash-like interface for `Literal::Data` and `Literal::Struct`

lib/literal/some.rb, test/literal/some.test.rb
=> Fix `Literal::Some` `#filter` and `#value_or`

lib/literal/generic.rb, lib/literal/method.rb
Update the abstract method logic to be stricter about parameters.
=> Strict abstract methods

lib/literal/lift.rb, test/literal/result.test.rb
Adds some tests to `#lift` and a couple of small fixes.
=> Fix bug in `lift` and add some tests

lib/literal/failure.rb, lib/literal/some.rb, lib/literal/success.rb, test/literal/maybe.test.rb
=> Add type safe transforms for Maybe objects

.rubocop.yml, lib/literal/failure.rb, literal.gemspec, test/literal/result.test.rb
Plus some tests and a commit just to bump Ruby dep to 3.2 as I see anonymous arguments used around now
=> `Failure` deconstruct additions

lib/literal/data_structure.rb, lib/literal/struct.test.rb
=> Marshal data structures

lib/literal/data_structure.rb, lib/literal/properties/schema.rb, lib/literal/property.rb, test/data.test.rb, test/properties.test.rb, test/struct.test.rb
Adds methods to help introspect properties, and makes the Schema enumerable
=> Proposed tweaks to properties

Gemfile.lock, lib/literal.rb, lib/literal/data_structure.rb, lib/literal/errors/type_error.rb, lib/literal/properties/schema.rb, lib/literal/property.rb, lib/literal/types/constraint_type.rb, lib/literal/types/float_type.rb, lib/literal/types/integer_type.rb, lib/literal/types/string_type.rb, lib/literal/types/symbol_type.rb, lib/literal/version.rb
First step towards better error messages in Literal.
Closes #97
=> Better error messages

lib/literal/types.rb
This PR introduces a number of shortcuts for billable types, such as `_Nil?`.
=> Nilable type shortcuts

lib/literal.rb, lib/literal/data_structure.rb, lib/literal/enum.rb, lib/literal/errors/type_error.rb, lib/literal/properties/schema.rb, lib/literal/property.rb, lib/literal/types/array_type.rb, lib/literal/types/map_type.rb, test/properties.test.rb
=> Add improved type errors with nested context

lib/literal/properties.rb, test/properties.test.rb
Should get the tests green on 3.2
=> Conditionally call Module#set_temporary_name

lib/literal/types/constraint_type.rb, lib/literal/types/tuple_type.rb, lib/literal/types/union_type.rb
This improves the performance of `_Constraint`, `_Tuple` and `_Union`.
=> Improve performance by reducing ivar reads

lib/literal.rb, lib/literal/array.rb, lib/literal/hash.rb, lib/literal/set.rb
Getting this in quickly so we can begin to iterate on adding methods.
=> Lay the groundwork for `Literal::Set` and `Literal::Hash`

lib/literal/array.rb
This one was present in my original PR but probably got lost during my screw up.
Addresses #169
=> Alias :eql? to :==

lib/literal/array.rb, test/array.test.rb
=> #uniq method and tests

Rakefile
I just checked out the repository and wanted to run the test suite 🙈
=> Fix test Rake task

lib/literal/array.rb, test/array.test.rb
=> Implement `Literal::Array#combination`

lib/literal/array.rb, test/array.test.rb
=> Implement `Literal::Array#delete`, `#delete_at` and `#delete_if`

lib/literal/array.rb, test/array.test.rb
=> Array#fetch (#170)

lib/literal/array.rb, test/array.test.rb
=> Implements #flatten method

lib/literal/array.rb, test/array.test.rb
=> Implements #flatten! method

lib/literal/array.rb, test/array.test.rb
I just copied the implementation of `Array#[]` without thinking too much in the previous PR.
=> Fix Array#fetch

lib/literal/array.rb, test/array.test.rb
=> Implements #inspect, #to_s

lib/literal/array.rb, test/array.test.rb
=> Implement #select and #select!

lib/literal/array.rb, test/array.test.rb
=> Implements #intersect? method

lib/literal/array.rb, test/array.test.rb
=> Implements `#join`, `#keep_if`

lib/literal/property.rb
basically the same as [this](https://github.com/joeldrapper/literal/pull/235)
cc @joeldrapper
=> Unable to have property named `property`

lib/literal/enum.rb
=> `Enum#to_h`

lib/literal/enum.rb
=> unique enum values

lib/literal/array.rb, test/array.test.rb
Closes #205.
Plus changes the title of the `#sort` test and adds one for `#sort!`.
=> Literal Array #sort_by!

lib/literal/array.rb, test/array.test.rb
=> Literal Array #take_while

lib/literal/types.rb, test/types.test.rb
=> Adding _Date, _Date?, _Time, and _Time? to Literal::Types

lib/literal/enum.rb
@joeldrapper I've noticed this error in our sentry some time ago, I guess it's an artifact from the past? Does that fix work?
=> fix enum type error

config/quickdraw.rb, lib/literal.rb, lib/literal/array.rb, lib/literal/transforms.rb, lib/literal/tuple.rb, lib/literal/types/class_type.rb, lib/literal/types/constraint_type.rb, lib/literal/types/deferred_type.rb, lib/literal/types/descendant_type.rb, lib/literal/types/enumerable_type.rb, lib/literal/types/frozen_type.rb, lib/literal/types/hash_type.rb, lib/literal/types/interface_type.rb, lib/literal/types/intersection_type.rb, lib/literal/types/map_type.rb, lib/literal/types/nilable_type.rb, lib/literal/types/not_type.rb, lib/literal/types/range_type.rb, lib/literal/types/set_type.rb, lib/literal/types/union_type.rb
Remove the `of` keyword argument and make it positional.
=> Simplify the subtype method

lib/literal/types/interface_type.rb, test/types/_interface.test.rb
When compared against a module, `_Interface` will inspect the instance methods defined on that module.
=> Improve interface type compaisons

lib/literal/array.rb, test/array.test.rb
=> Implements `#reverse` in Literal::Array

lib/literal/array.rb, test/array.test.rb
=> Implements `#reverse!` in Literal::Array
