yippee-fun/literal

- .gitignore
- lib/literal/lift.rb
- test/literal/result.test.rb
`return @failure_case&.call(value)` will return `nil` before it gets to the `raise` when not supplied a `.failure` block calling `.lift!`
> fix `lift!` behavior without `.failure` case

- lib/literal/nothing_class.rb
- lib/literal/some.rb
- test/literal/nothing.test.rb
- test/literal/some.test.rb
For Some, `<=>` and `eql?` depend on its value, making them more 'value class' like
Fixes #32
> Make `Literal::Maybe` subclasses comparable. 

- .github/workflows/ruby.yml
- bin/console
- lib/literal/enum.rb
- test/literal/enum.test.rb
Tweaks implementation regexs, adds `.to_proc` as alias to `cast` so you can do something like `[0, 4].map(&Color)) ` => ` [Color::Red, Color::LightRed]`
> Enums tweaks

- lib/literal/array_type.rb
- lib/literal/constructors.rb
- lib/literal/enum.rb
- lib/literal/enum_type.rb
- test/literal/array.test.rb
- test/literal/enum.test.rb
With this change, you can now define Enums more like normal classes.
```ruby
class Color < Literal::Enum(Integer)
Red(0)
Green(1)
Blue(2)
end
```
This allows you to use relative constants, e.g.
```ruby
class Switch < Literal::Enum(_Boolean)
On(true) do
def toggle = Off
end
Off(false) do
def toggle = On
end
end
```
> Define enums as normal classes

- lib/literal/enum.rb
- lib/literal/module_defined.rb
- test/literal/enum.test.rb
In this PR, I’m adding an `index` macro to `Enum`, which allows you to generate Hash indexes for `O(1)` lookups. The index can be generated from any attribute or Proc calculation on a member.
```ruby
class Language < Literal::Enum(Integer)
index :name, String, unique: true
EN(0) do
def name = "English"
end
FR(1) do
def name = "French"
end
end
Language.where(name: "English") # => [Language::EN]
Language.find_by(name: "English") # => Language::EN
```
You can only use `find_by` for unique indexes.
The indexes are generated using a Proc, which defaults to `name.to_proc`, however you a pass a block instead.
```ruby
index :name, String, unique: true do |language|
language.name.upcase
end
```
> Literal::Enum indexes

- lib/literal/attributable.rb
- lib/literal/data_enum.rb
- lib/literal/enum.rb
- test/literal/data_enum.test.rb
- test/literal/enum.test.rb
I’ve removed the `index` feature from #64 and added a new kind of enum that's better for working with static enumerations of data objects. Standard enums are better for simple key/value enumerations and IMO don't need indexes.
> Literal::DataEnums

- Gemfile.lock
The jaro_winkler library has an error when compiling on LLVM 15.
> Update jaro_winkler development version

- Rakefile
I'm sure this will change again eventually when moving to `quickdraw`, but for now, just shell out to `gd`.
> Update rake test task to call greendots

- lib/literal/structish.rb
- test/literal/struct.test.rb
as per Ruby docs, mostly this is just an alias of #==
> Structish classes should define eql?

- lib/literal.rb
- lib/literal/enum.rb
- test/enum.test.rb
This PR introduces a number of changes and improvements to Literal::Enums.
Literal::Enums no longer use `method_missing` to provide a "literal" syntax. Instead, you assign constants yourself.
```ruby
class Color < Literal::Enum(Integer)
Red = new(1)
Green = new(2)
Blue = new(3)
end
```
The advantage to this is language servers can pick up the constants and they’ll know the types because of the call to `new`.
Every enum class has a `value` property which is specified in the class you inherit from. This will always be the first positional argument and it’s how the Enum can be efficiently coerced back and forth from a simple value for storage.
Enum classes will be frozen after definition, so you can’t add any new constants.
You can look up a list of members or values:
```ruby
Color.members # …
```
> Better Enums

- lib/literal/enum.rb
- test/enum.test.rb
It is possible to do `Enum.to_set` and `Enum.to_a` but not `Enum.to_h`
```
Switch.to_h
ruby/3.3.0/lib/ruby/3.3.0/set.rb:501:in `each_key': wrong element type Switch (expected array) (TypeError)
@hash.each_key(&block)
^^^^^^
```
We can implement it to either:
return a hash where the values are the keys and the Enum instances are the values. 
`{ true => Switch::On, false => Switch::Off }`
Or vice versa
`{ Switch::On => true, Switch::Off => false }`
The more semantically intuitive is the latter I think, but then again, `.[]` actually maps enum values to instances, so the former aligns better with that.
This PR implements it as the former, ie 
```
irb(main):007> Switch[true]
=> Switch::On
irb(main):008> Switch.to_h
=> {true=>Switch::On, false=>Switch::Off}
irb(main):009> Switch.to_h[true] 
=> …
```
> Implement Enum.to_h

- lib/literal/properties/schema.rb
@joeldrapper I'm not sure in what cases you can hit this but I did. I guess if you have lots of properties defined. But in that case `positional` arguments can change their order which brakes things. By unstable sort I mean that the sorting algorithm(it being quicksort) does not preserve the original ordering of elements that are equal to each other
update:
here's how to reproduce:
```ruby
class Example
extend Literal::Properties
10.times { |t| prop :"prop#{t}", _Any, :positional }
end
Example.literal_properties # => ❗️ @properties_index and @sorted_properties are in different order
```
> fix unstable sorting

- lib/literal/data_structure.rb
- test/data.test.rb
Need `eql?` in addition to `==`
> Allow data structures to be used as hash keys

- lib/literal/data_structure.rb
- lib/literal/properties.rb
- test/data.test.rb
- test/properties.test.rb
This reverts commit 797b227e1cb554a7726e8aa97c3879ea067ba6d6.
Fix was continuing to include the `include(__literal_extension__)` call on every call to `prop` ...
> Reapply "Ensure empty properties/datas/structs work as expected (#111)"

- test/properties.test.rb
TruffleRuby and JRuby backtraces are slightly different to CRuby backtraces.
> Use the generated backtrace in error message assertions

- lib/literal/properties/schema.rb
Aliasing the method before redefining it supresses the warning
> Avoid method redefinition warnings

- lib/literal.rb
- lib/literal/array.rb
- test/array.test.rb
> Prototype Literal::Array

- lib/literal/array.rb
- test/array.test.rb
Add support for the bitwise AND operator on `Literal::Array`s.
See #134
> `Literal::Array#&`

- lib/literal/array.rb
- test/array.test.rb
Related to #134 
*** 
The current implementation of `#push` was only allowing for one value to
be passed in, but if the goal is to match [ruby's functionality](https://ruby-doc.org/3.3.6/Array.html#method-i-push), then it
should accept multiple.
We also want to ensure that we perform the right type checking logic for
both scenarios.
> make `Literal::Array#push` accept multiple values

- lib/literal.rb
- lib/literal/type.rb
- lib/literal/types.rb
- lib/literal/types/boolean_type.rb
- test/types.test.rb
In order to avoid type checks on some Literal::Array, Literal::Hash and Literal::Set operations, we will need to be able to establish if one type is a subtype of another type.
We can already do this with Modules, using `<`, `==`, and `>`. I think we should be able to do it for Literal types too. For example, `true` and `false` are sub types of `_Boolean`.
If you’re merging a `Literal::Array(true)` into a `Literal::Array(_Boolean)`, you should not have to check its types.
> Initial capabilities for covariant types

- lib/literal/array.rb
- test/array.test.rb
Continuing to chip away at #134 
*** 
My goal was to more or less work my way down the list of "Methods for Assigning" from the ruby docs
From that list, this implements:
- `#prepend` (alias for `#unshift`)
- `#insert`
- `#replace`
I'm still not 100% on if I'm always using `Literal.check` correctly. And also unsure how thorough to be in tests. Feedback welcome of course!
> Literal::Array: implement `#replace`, and `#insert`. add `#prepend` alias

- lib/literal/properties.rb
If a YARD docstring is added that defines initializer as forwarding all arguments, IDEs like RubyMine maybe happier with the lack of a statically visible initialize definition
> YARD docstring that defines initializer as forwarding all args, stops RubyMine warnings

- lib/literal/array.rb
- test/array.test.rb
Implementation and tests for:
- `Literal::Array#*`
- `Literal::Array#+`
- `Literal::Array#-`
Closes #152
Closes #151 
Closes #153 
Closes #156 
Closes #160 
Closes #162 
Closes #184
> Implement some methods on Literal::Array

- lib/literal/array.rb
`Array` has aliases `#map -> #collect`  and `#map! -> #collect!`
This change add `Literal::Array` aliases `#collect -> #map` and `#collect! -> #map!`. 
While it wouldn't change the functionality, it may be worth switching the alias and the target to match the ruby implementation.
> Add aliases for `Literal::Array#collect` and `#collect!`

- lib/literal/data_property.rb
- test/data.test.rb
When `dup`ing  a property we can lose some attributes. So e.g.:
```ruby
class Ex < Literal::Data
prop :record, Book
end
record = Book.find(1)
ex = Ex.new(record:)
ex.record # => <Book id: nil>
```
because rails's dup does not preserve ids(and some other things)
cc @joeldrapper
> Fix data property dup

- lib/literal/enum.rb
- test/enum.test.rb
If `Literal::Enum.to_h` yields members, it will be much easier to construct your own `to_h` blocks using `it`. Additionally, the default `to_h` now maps members to values. Previously, this was the other way around.
> Literal::Enum.to_h should yield members, not values

- lib/literal.rb
- lib/literal/property.rb
Maintaining and testing this option is very difficult, and the type checks are so fast it’s not necessary. Also, this was never part of the public API so it should be safe to remove.
> Remove the option to disable checks

- lib/literal/enum.rb
- lib/literal/rails/enum_type.rb
- test/enum.test.rb
This PR makes it possible to coerce enums from their constant name as a symbol.
```ruby
class Color < Literal::Enum(Integer)
Red = new(1)
Green = new(2)
Blue = new(3)
end
Color.coerce(:Red) # => Color::Red
```
Since `.to_proc` maps to coerce, this means you can use it as a literal property coercion.
```ruby
class MyThing
prop :color, Color, &Color
end
MyThing.new(color: :Red)
```
This is useful if the property itself already has the context of the enum.
> Allow enum coercion from symbol

- lib/literal/array.rb
- lib/literal/tuple.rb
- test/array.test.rb
This allows us to transpose a `Literal::Array(Literal::Tuple)` to a new tuple of arrays of the correct type.
> Literal::Array(Literal::Tuple)#transpose

- lib/literal/array.rb
- test/array.test.rb
> `Literal::Array(T)` coercion

- lib/literal/array.rb
- test/array.test.rb
This allows you to zip a Literal::Array with other Arrays or Literal::Arrays returning a Literal::Array of Literal::Tuples.
Closes #216
> Literal::Array#zip

- lib/literal.rb
- lib/literal/enum.rb
- test/enum.test.rb
Enums are now by default ordered by their definition order, which means they are now range-able.
> Make enums ordered

- Gemfile
- config/quickdraw.rb
- lib/literal/rails/patches/active_record.rb
- test/rails.test.rb
It seems like a wrong way to build Literal::TypeError
```
NoMethodError (undefined method 'expected' for class Literal::TypeError):
literal (1.4.0) lib/literal/rails/patches/active_record.rb:7:in 'ActiveRecord::RelationType#initialize'
literal (1.4.0) lib/literal/rails/patches/active_record.rb:29:in 'Class#new'
literal (1.4.0) lib/literal/rails/patches/active_record.rb:29:in 'ActiveRecord.Relation'
```
> Fix error when using non-ActiveRecord::Base on ActiveRecord::Relation

- Gemfile
- test/rails.test.rb
My last PR broke CI:
- JRuby tests were broken because Rails was added as `platform: ruby` dependency
- Rubocop was complaining about missing frozen string literal comment.
Sorry.
> Fixing Rubocop and JRuby CI

- lib/literal/properties/schema.rb
- test/data.test.rb
The generated `==` methods on data structures were assuming each property had a reader, which is not necessary the case. It is possible to disable readers for properties.
> Fix data structure `==` equality

- lib/literal/rails/enum_type.rb
@joeldrapper I think this would make sense
https://github.com/rails/rails/blob/00cc4ff0259c0185fe08baadaa40e63ea2534f6e/activemodel/lib/active_model/type/value.rb#L32
> add `type`

- lib/literal/types.rb
- test/types.test.rb
When a constraint has only one argument, it can be flattened to that argument.
> Flatten constraints

- lib/literal/properties/schema.rb
- test/properties.test.rb
`after_initialize` hook comes very handy with `Literal::Data`, when we want to, for example freeze some of the complex properties passed in. But making this method public seems a bit incorrect.
> feat: Allow private-scoped after_initialize hooks

- lib/literal.rb
- lib/literal/delegator.rb
- lib/literal/value.rb
- test/delegator.test.rb
- test/value.test.rb
This PR introduces `Literal::Value` objects. Literal::Values are designed to wrap primitives (though they can wrap any object) in a branded object allowing for more precise type-matching.
```ruby
UserID = Literal::Value(Integer)
my_user_id = UserID.new(123)
```
You can pass constraints, same as `_Constraint`
```ruby
Username = Literal::Value(String, length: 3..15)
```
Literal value classes can be coerced into a coercion by default
```ruby
prop :user, UserID, &UserID
```
You can delegate to underlying methods
```ruby
Username = Literal::Value(String) do
delegate :length
end
```
Literal will default to delegating to basic coercion methods. For example, if your value is a String, it will delegate `to_s` and `to_str` to the underlying value by default. Otherwise, delegation is explicit.
Only …
> Value objects

- lib/literal.rb
- lib/literal/brand.rb
- test/brand.test.rb
This is similar to #293 but instead of wrapping values, you can brand values. The values themselves are unchanged and not wrapped.
> Literal branded types

- lib/literal/enum.rb
- test/enum.test.rb
Rationale
---------
This is a very personal preference, but I like enum members to be all-caps. Currently, if such a member name has underscores in it, e.g. `WHY_NOT`, the generated predicate name is `why__not?`.
Example
-------
``` ruby
class Lead < Literal::Enum(String)
FRIENDS_AND_FAMILY = new("friends_and_family")
OTHER              = new("other")
end
Lead.members.sample.friends_and_family?
```
> feat: Better predicates support for SCREAMING_ENUM

- lib/literal/data_structure.rb
- lib/literal/properties.rb
- lib/literal/properties/schema.rb
- test/data.test.rb
This allows using `Literal::Data` (and its friends) like so:
``` ruby
class Person < Literal::Data
prop :first_name, String
prop :last_name,  String
end
john = Person.new(first_name: "John", last_name: "Doe")
jane = Person.new(**john, first_name: "Jane")
```
This is especially useful when we use Data/Struct as configuration options data:
``` ruby
class Shrine
module Plugins
module Example
class Options < Literal::Data
end
DEFAULT_OPTIONS = { ... }
def self.configure(uploader, **options)
uploader.opts[:example] = Options.new(
**DEFAULT_OPTIONS,
**uploader.opts[:example],
**options
)
end
end
register_plugin(:example, Example)
end
end
```
> feat: Make data structs implicitly Hash coercible

- lib/literal.rb
- lib/ruby_lsp/literal/addon.rb
Set up basic Ruby LSP add-on. This add-on defines instance variables when you use the `prop` macro. It also sets up reader and writer methods with the correct visibility, but only when you specify them directly in the macro.
> Ruby LSP extension

- lib/literal/data.rb
- test/data.test.rb
Proposal:
[Native Data structure](https://docs.ruby-lang.org/en/master/Data.html#method-c-new) allows objects to be instantied using `[]`, eg.
```ruby
Measure = Data.define(:amount, :unit)
Measure.new(amount: 1, unit: 'km')
#=> #<data Measure amount=1, unit="km">
Measure[amount: 1, unit: 'km']
#=> #<data Measure amount=1, unit="km">
```
I think Literal::Data should allow this syntax too to have an DX closer to native Data structure. It was the first way I tried to instance a Literal::Data and I got an error `undefined method '[]' for class Xyz`.
> Allow `[]` to initialize Literal::Data

- lib/literal/data.rb
- test/data.test.rb
Proposal:
It would be nice to have a `define` like the [native Data structure](https://docs.ruby-lang.org/en/master/Data.html). It is useful for code like this:
```ruby
class CreateUser 
Success = Class.new(Literal::Data) do
prop :user, User
end
Failure = Class.new(Literal::Data) do
prop :reason, Symbol
prop :user, User
end
end
class CreateUser 
Success = Literal::Data.define(user: User)
Failure = Literal::Data.define(reason: Symbol, user: User)
end
```
With this define, we lose the ability to specify kind, reader, predicate, and default values, but I believe the goal is to provide a straightforward way to define simple data structures.
> Implement Literal::Data.define

- lib/literal/enum.rb
- test/enum.test.rb
This changes the behavior of `to_s` and `to_sym` on Enums.
`to_s` returns a humanized version of the demodularized class name, eg: "Red," "Slate gray," "Spring green"
`to_sym` converts the demodularized class name to a symbol, eg: `:Red`, `:SlateGray`, `:SPRING_GREEN`
Note that this was deemed a minor breaking change.
> Change behavior of Enum's to_s and to_sym methods
